In [ ]:
from sklearn import preprocessing
import numpy as np

1. data normalization (Done!)
2. basic tensor operations
3. linear regression
4. MLP+logistic regression
5. CNNs
5. RNNs
6. Attn_RNNs
7. AutoEncoder

* X_train: input data with 3 time series and 5 time steps

In [ ]:
X_train = np.array([[ 1., -1.,  2., 3,  1],
...                     [ 2.,  0.,  0., 1, 2],
...                     [ 0.,  1., -1., -1, 3]])

X_test = np.array([[ 1., 0.,  1., -1,  1],
...                     [ 2.,  1.,  3., 1, 2],
...                     [ 1.,  1., -1., 1, -2]])


* **Standarlization** data with zero mean and unit variance.

In [ ]:
scaler = preprocessing.StandardScaler().fit(X_train.T)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
# mean
print(scaler.mean_)
# std
print(scaler.scale_)

[1.2 1.  0.4]
[1.32664992 0.89442719 1.49666295]


In [ ]:
# standarlized training data
scaler.transform(X_train.T).T

array([[-0.15075567, -1.6583124 ,  0.60302269,  1.35680105, -0.15075567],
       [ 1.11803399, -1.11803399, -1.11803399,  0.        ,  1.11803399],
       [-0.26726124,  0.40089186, -0.93541435, -0.93541435,  1.73719807]])

In [ ]:
# standarlized test data
scaler.transform(X_test.T).T

array([[-0.15075567, -0.90453403, -0.15075567, -1.6583124 , -0.15075567],
       [ 1.11803399,  0.        ,  2.23606798,  0.        ,  1.11803399],
       [ 0.40089186,  0.40089186, -0.93541435,  0.40089186, -1.60356745]])

* **Scaling** features to a range between 0 and 1

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()

In [ ]:
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [ ]:
X_train_minmax

array([[0.5       , 0.        , 1.        , 1.        , 0.        ],
       [1.        , 0.5       , 0.33333333, 0.5       , 0.5       ],
       [0.        , 1.        , 0.        , 0.        , 1.        ]])